"use strict";

const STORAGE_KEY = "Nodix_mercancia_v1";
const dialog = document.getElementById("merchandiseDialog");
const form = document.getElementById("merchandiseForm");
const rows = document.getElementById("merchandiseRows");
const emptyState = document.getElementById("emptyState");
const search = document.getElementById("searchMerchandise");
const message = document.getElementById("formMessage");
const toast = document.getElementById("toast");
let entries = readEntries();
let editingId = "";
let toastTimer;
const money = value => new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(Number(value) || 0);
const safe = value => String(value || "").replace(/[&<>'"]/g, character => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" }[character]));
function readEntries() { try { const data = JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]"); return Array.isArray(data) ? data.map(normalize) : []; } catch { return []; } }
function normalize(item) { const cantidad = Number(item.cantidad) || 0; const costo = Number(item.costo) || 0; return { id: String(item.id || `MER-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`), descripcion: String(item.descripcion || "").trim(), cantidad, costo, valorTotal: Number(item.valorTotal) || cantidad * costo, fecha: String(item.fecha || "").slice(0, 10) }; }
function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify(entries)); }
function filtered() { const query = search.value.trim().toLowerCase(); return entries.filter(item => `${item.descripcion} ${item.fecha}`.toLowerCase().includes(query)); }
function render() { const visible = filtered(); document.getElementById("totalEntries").textContent = entries.length; document.getElementById("totalQuantity").textContent = entries.reduce((sum, item) => sum + item.cantidad, 0); document.getElementById("merchandiseValue").textContent = money(entries.reduce((sum, item) => sum + item.valorTotal, 0)); document.getElementById("resultsCount").textContent = `${visible.length} ${visible.length === 1 ? "registro" : "registros"}`; rows.innerHTML = visible.map(item => `<tr><td class="document-cell"><strong>${safe(item.descripcion || "Sin descripción")}</strong></td><td class="phone-cell">${item.cantidad}</td><td class="phone-cell">${money(item.costo)}</td><td class="phone-cell">${money(item.valorTotal)}</td><td class="phone-cell">${safe(item.fecha || "—")}</td><td><div class="row-actions"><button class="icon-button" type="button" data-action="edit" data-id="${safe(item.id)}" aria-label="Editar entrada"><i class="fa-solid fa-pen" aria-hidden="true"></i></button><button class="icon-button" type="button" data-action="delete" data-id="${safe(item.id)}" aria-label="Eliminar entrada"><i class="fa-solid fa-trash" aria-hidden="true"></i></button></div></td></tr>`).join(""); emptyState.hidden = visible.length > 0; if (!visible.length) { const filteredBySearch = Boolean(search.value.trim()); document.getElementById("emptyTitle").textContent = filteredBySearch ? "No encontramos coincidencias" : "Aún no hay mercancía"; document.getElementById("emptyText").textContent = filteredBySearch ? "Prueba con otra búsqueda." : "Registra la primera entrada para comenzar."; document.getElementById("emptyAction").hidden = filteredBySearch; } }
function showToast(text) { clearTimeout(toastTimer); toast.textContent = text; toast.classList.add("show"); toastTimer = setTimeout(() => toast.classList.remove("show"), 2300); }
function updateTotal() { document.getElementById("valorTotal").value = ((Number(document.getElementById("cantidad").value) || 0) * (Number(document.getElementById("costo").value) || 0)).toFixed(2); }
function resetForm() { editingId = ""; form.reset(); document.getElementById("dialogTitle").textContent = "Nueva entrada"; document.getElementById("fecha").value = new Date().toISOString().slice(0, 10); document.getElementById("valorTotal").value = ""; message.textContent = ""; }
function openDialog(item) { resetForm(); if (item) { editingId = item.id; document.getElementById("dialogTitle").textContent = "Editar entrada"; document.getElementById("merchandiseId").value = item.id; document.getElementById("descripcion").value = item.descripcion; document.getElementById("cantidad").value = item.cantidad; document.getElementById("costo").value = item.costo; document.getElementById("valorTotal").value = item.valorTotal.toFixed(2); document.getElementById("fecha").value = item.fecha; } if (dialog.showModal) dialog.showModal(); else dialog.setAttribute("open", ""); setTimeout(() => document.getElementById("descripcion").focus(), 0); }
function closeDialog() { if (dialog.open && dialog.close) dialog.close(); else dialog.removeAttribute("open"); resetForm(); }
document.getElementById("newMerchandise").addEventListener("click", () => openDialog()); document.getElementById("emptyAction").addEventListener("click", () => openDialog()); document.getElementById("closeDialog").addEventListener("click", closeDialog); document.getElementById("cancelDialog").addEventListener("click", closeDialog); dialog.addEventListener("click", event => { if (event.target === dialog) closeDialog(); }); search.addEventListener("input", render); document.getElementById("cantidad").addEventListener("input", updateTotal); document.getElementById("costo").addEventListener("input", updateTotal);
rows.addEventListener("click", event => { const button = event.target.closest("button[data-action]"); if (!button) return; const item = entries.find(entry => entry.id === button.dataset.id); if (!item) return; if (button.dataset.action === "edit") openDialog(item); if (button.dataset.action === "delete" && window.confirm("¿Eliminar esta entrada de mercancía?")) { entries = entries.filter(entry => entry.id !== item.id); persist(); render(); showToast("Entrada eliminada"); } });
form.addEventListener("submit", event => { event.preventDefault(); message.textContent = ""; if (!form.reportValidity()) return; const values = Object.fromEntries(new FormData(form).entries()); const current = entries.find(item => item.id === editingId); const wasEditing = Boolean(editingId); const record = normalize({ ...current, id: editingId || `MER-${Date.now()}`, descripcion: values.descripcion.trim(), cantidad: values.cantidad, costo: values.costo, valorTotal: values.valorTotal, fecha: values.fecha }); entries = wasEditing ? entries.map(item => item.id === editingId ? record : item) : [record, ...entries]; persist(); closeDialog(); render(); showToast(wasEditing ? "Entrada actualizada" : "Entrada creada"); });
render();
