"use strict";

const STORAGE_KEY = "Nodix_clientes_v1";
const dialog = document.getElementById("clientDialog");
const form = document.getElementById("clientForm");
const rows = document.getElementById("clientsRows");
const emptyState = document.getElementById("emptyState");
const search = document.getElementById("searchClients");
const message = document.getElementById("formMessage");
const toast = document.getElementById("toast");
let clients = readClients();
let editingId = "";
let toastTimer;
const safe = value => String(value || "").replace(/[&<>'"]/g, character => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" }[character]));
const initials = name => String(name || "N").trim().split(/\s+/).slice(0, 2).map(part => part[0]).join("").toUpperCase() || "N";
function readClients() { try { const data = JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]"); return Array.isArray(data) ? data.map(normalize) : []; } catch { return []; } }
function normalize(item) { return { id: String(item.id || item.documento || `CLI-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`), documento: String(item.documento || "").trim(), nombre: String(item.nombre || "").trim(), telefono: String(item.telefono || "").trim() }; }
function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify(clients)); }
function filtered() { const query = search.value.trim().toLowerCase(); return clients.filter(item => `${item.documento} ${item.nombre} ${item.telefono}`.toLowerCase().includes(query)); }
function render() { const visible = filtered(); document.getElementById("totalClients").textContent = clients.length; document.getElementById("clientsWithPhone").textContent = clients.filter(item => item.telefono).length; document.getElementById("lastClient").textContent = clients[0] ? (clients[0].nombre.split(" ")[0] || "—") : "—"; document.getElementById("resultsCount").textContent = `${visible.length} ${visible.length === 1 ? "registro" : "registros"}`; rows.innerHTML = visible.map(item => `<tr><td><div class="person-cell"><span class="avatar">${safe(initials(item.nombre))}</span><span><strong>${safe(item.nombre || "Sin nombre")}</strong><small>Cliente registrado</small></span></div></td><td class="document-cell">${safe(item.documento || "—")}</td><td class="phone-cell">${safe(item.telefono || "—")}</td><td><div class="row-actions"><button class="icon-button" type="button" data-action="edit" data-id="${safe(item.id)}" aria-label="Editar cliente"><i class="fa-solid fa-pen" aria-hidden="true"></i></button><button class="icon-button" type="button" data-action="delete" data-id="${safe(item.id)}" aria-label="Eliminar cliente"><i class="fa-solid fa-trash" aria-hidden="true"></i></button></div></td></tr>`).join(""); emptyState.hidden = visible.length > 0; if (!visible.length) { const filteredBySearch = Boolean(search.value.trim()); document.getElementById("emptyTitle").textContent = filteredBySearch ? "No encontramos coincidencias" : "Aún no hay clientes"; document.getElementById("emptyText").textContent = filteredBySearch ? "Prueba con otra búsqueda." : "Crea el primer registro para comenzar."; document.getElementById("emptyAction").hidden = filteredBySearch; } }
function showToast(text) { clearTimeout(toastTimer); toast.textContent = text; toast.classList.add("show"); toastTimer = setTimeout(() => toast.classList.remove("show"), 2300); }
function resetForm() { editingId = ""; form.reset(); document.getElementById("dialogTitle").textContent = "Agregar cliente"; message.textContent = ""; }
function openDialog(item) { resetForm(); if (item) { editingId = item.id; document.getElementById("dialogTitle").textContent = "Editar cliente"; document.getElementById("clientId").value = item.id; document.getElementById("documento").value = item.documento; document.getElementById("nombre").value = item.nombre; document.getElementById("telefono").value = item.telefono; } if (dialog.showModal) dialog.showModal(); else dialog.setAttribute("open", ""); setTimeout(() => document.getElementById("documento").focus(), 0); }
function closeDialog() { if (dialog.open && dialog.close) dialog.close(); else dialog.removeAttribute("open"); resetForm(); }
document.getElementById("newClient").addEventListener("click", () => openDialog()); document.getElementById("emptyAction").addEventListener("click", () => openDialog()); document.getElementById("closeDialog").addEventListener("click", closeDialog); document.getElementById("cancelDialog").addEventListener("click", closeDialog); dialog.addEventListener("click", event => { if (event.target === dialog) closeDialog(); }); search.addEventListener("input", render);
rows.addEventListener("click", event => { const button = event.target.closest("button[data-action]"); if (!button) return; const item = clients.find(client => client.id === button.dataset.id); if (!item) return; if (button.dataset.action === "edit") openDialog(item); if (button.dataset.action === "delete" && window.confirm(`¿Eliminar a ${item.nombre || "este cliente"}?`)) { clients = clients.filter(client => client.id !== item.id); persist(); render(); showToast("Cliente eliminado"); } });
form.addEventListener("submit", event => { event.preventDefault(); message.textContent = ""; if (!form.reportValidity()) return; const values = Object.fromEntries(new FormData(form).entries()); const documentValue = values.documento.trim(); if (clients.some(item => item.documento.toLowerCase() === documentValue.toLowerCase() && item.id !== editingId)) { message.textContent = "Ya existe un cliente con ese documento."; return; } const current = clients.find(item => item.id === editingId); const wasEditing = Boolean(editingId); const record = normalize({ ...current, id: editingId || `CLI-${Date.now()}`, documento: documentValue, nombre: values.nombre.trim(), telefono: values.telefono.trim() }); clients = wasEditing ? clients.map(item => item.id === editingId ? record : item) : [record, ...clients]; persist(); closeDialog(); render(); showToast(wasEditing ? "Cliente actualizado" : "Cliente creado"); });
render();
